apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service    # Service name
spec:
  selector:
    app: reddit-clone          # Selects pods with the label 'app: reddit-clone'
  ports:
  - port: 3000                  # Port exposed by the service
    targetPort: 3000            # Port to which the service forwards traffic
    protocol: TCP               # Protocol used for the service (TCP in this case)
  type: LoadBalancer            # Type of service (LoadBalancer)
